# Файл docker-compose начинается с тега версии.
version: '3.8'

# List all used services (web & db) with which we can interact with the console
services:

# The first service is a web application
  web:
  # Path to the Dockerfile to create the image that starts the service
    build: .
    # The command will work on completion of the image
    command: python manage.py runserver 0.0.0.0:8000
    # Data save address
    volumes:
      - .:/trade_car_app
    ports:
      - 8000:8000
    # We collect the virtual machine from the current directory - .env
    env_file:
      - .env
    # Service startup dependency
    depends_on:
      # the web application will wait for the db service to start
      - db

  # The second service is the database
  db:
    # Image obtained from dockerhub
    image: postgres:13.0-alpine
    # Data save address
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # Database variables
    env_file:
      - .env

volumes:
  postgres_data:
