version: '3.8'

services:

  # Database service
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - .env.prod

  # Redis service
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    depends_on:
      - db

# Web application service
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn admin.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/trade_car_app/static/
    expose:
      - 8000
    env_file:
      - .env.prod
    depends_on:
      - db
      - redis

  # Worker celery service
  worker:
    build: .
    command: celery -A admin worker --loglevel=info --logfile=data/celery.log
    env_file:
      - .env
    volumes:
      - .:/trade_car_app
    depends_on:
      - web

  # Celery beat service
  beat:
    build: .
    command: celery -A admin beat -l info
    env_file:
      - .env
    volumes:
      - .:/trade_car_app
    depends_on:
      - worker

  # Flower service
  flower:
    build: .
    command: celery -A admin flower
    volumes:
      - .:/trade_car_app
    # working_dir: /data
    ports:
      - 5555:5555
    env_file:
      - .env
    depends_on:
      - beat

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/trade_car_app/static/
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
